document.addEventListener("DOMContentLoaded", function() {
document.querySelector(".header").innerHTML=`<nav class="navbar"><div class="logo"><i class="fas fa-code"></i> Adarsh</div><ul class="nav-links"><li><a href="#home">Home</a></li><li><a href="#about">About</a></li><li><a href="#services">Services</a></li><li><a href="#projects">Projects</a></li><li><a href="#pricing">Pricing</a></li><li><a href="#contact">Contact</a></li></ul><a href="https://wa.me/918298827509" class="btn-hire">Hire Me</a></nav>`;
document.querySelector(".hero").innerHTML=`<div class="container" style="display:flex;align-items:center;gap:50px;justify-content:space-between;"><div class="hero-text"><h3>I Design & Build</h3><h1>Modern Websites That <span>Grow Business</span></h1><p>Helping businesses & entrepreneurs with stunning, fast & conversion focused websites in Jharkhand.</p><div class="btn-group"><a href="#projects" class="btn-primary">View Projects</a><a href="#contact" class="btn-secondary">Let's Talk</a></div></div><div><img src="https://via.placeholder.com/500x400/00C897/0A0F1A?text=Laptop+Mockup" style="border-radius:20px;max-width:100%;"></div></div>`;
document.querySelector(".about").innerHTML=`<div class="container"><h2 class="section-title">About <span>Me</span></h2><div style="display:flex;gap:50px;align-items:center;flex-wrap:wrap;"><img src="https://via.placeholder.com/400x500/111827/00C897" style="border-radius:16px;border:2px solid var(--primary);max-width:100%;"><div style="flex:1;"><h3>Premium Web Designer & Developer</h3><p style="color:var(--text-gray);margin:20px 0;line-height:1.8;">मैं Adarsh Tiwari। मेरा mission है Jharkhand के businesses को ऐसी website देना जो देखने में लाखों की लगे और sales लाए। 3+ साल का experience, 50+ projects.</p><p><b style="color:var(--primary);">Email:</b> adarsh.web@gmail.com</p><p><b style="color:var(--primary);">Location:</b> Daltonganj, Jharkhand, India</p></div></div></div>`;
document.querySelector(".services").innerHTML=`<div class="container"><h2 class="section-title">My <span>Services</span></h2><div class="services-grid">${['Web Design','E-Commerce','SEO','UI/UX','WordPress','Maintenance'].map(s=>`<div class="service-card"><i class="fas fa-check"></i><h3 style="margin:15px 0;">${s}</h3><p style="color:var(--text-gray);">Premium quality service with 100% client satisfaction.</p></div>`).join('')}</div></div>`;
document.querySelector(".skills").innerHTML=`<div class="container"><h2 class="section-title">My <span>Skills</span></h2><p style="text-align:center;color:var(--text-gray);">HTML, CSS, JavaScript, React, WordPress, Shopify, Figma</p></div>`;
document.querySelector(".process").innerHTML=`<div class="container"><h2 class="section-title">My <span>Process</span></h2><p style="text-align:center;color:var(--text-gray);">1. Discover > 2. Design > 3. Develop > 4. Deliver</p></div>`;
document.querySelector(".projects").innerHTML=`<div class="container"><h2 class="section-title">My <span>Projects</span></h2><p style="text-align:center;color:var(--text-gray);">6+ Premium Projects Coming Soon</p></div>`;
document.querySelector(".pricing").innerHTML=`<div class="container"><h2 class="section-title">Pricing <span>Packages</span></h2><p style="text-align:center;color:var(--text-gray);">Basic, Pro, Premium Plans</p></div>`;
document.querySelector(".testimonials").innerHTML=`<div class="container"><h2 class="section-title">Client <span>Feedback</span></h2><p style="text-align:center;color:var(--text-gray);">"Best Designer in Jharkhand" - Client</p></div>`;
document.querySelector(".achievements").innerHTML=`<div class="container"><h2 class="section-title">My <span>Achievements</span></h2><p style="text-align:center;color:var(--text-gray);">50+ Projects | 30+ Clients | 5 Star Rating</p></div>`;
document.querySelector(".faq").innerHTML=`<div class="container"><h2 class="section-title">FAQ</h2><p style="text-align:center;color:var(--text-gray);">Common Questions</p></div>`;
document.querySelector(".blog").innerHTML=`<div class="container"><h2 class="section-title">Latest <span>Blog</span></h2><p style="text-align:center;color:var(--text-gray);">Tips for Business Growth</p></div>`;
document.querySelector(".contact").innerHTML=`<div class="container"><h2 class="section-title">Get In <span>Touch</span></h2><form class="contact-form" style="max-width:600px;margin:auto;display:flex;flex-direction:column;gap:20px;"><input type="text" placeholder="Your Name" required><input type="email" placeholder="Your Email" required><textarea placeholder="Message" rows="5" required></textarea><button class="btn-primary">Send Message</button></form></div>`;
document.querySelector(".footer").innerHTML=`<div style="text-align:center;padding:30px;border-top:1px solid #1F2937;color:var(--text-gray);"><p>© 2026 Adarsh Tiwari. No.1 Web Designer in Jharkhand.</p></div>`;
window.addEventListener("load", ()=>{document.querySelector(".loader").style.display="none";});
});
